#主要服务器配置,核心库相关配置
server:
  host: 0.0.0.0
  port: 3001
  #Cookie的存活时间,默认1小时
  tokenMaxAge: 3600
  production: false

mysql:
  #注意,如果使用docker部署,host是service名字,如db
  host: localhost
  port: 3306
  user: root
  password: root
  dbname: personalbill
  charset: "utf8mb4"

redis:
  #注意,如果使用docker部署,host是service名字,如redis
  host: localhost
  port: 6379
  password:
  prefix: bill
  maxIdle: 3
  maxActive: 5

xorm:
  showSql: true
  logLevel: 1
  timezone: "Asia/Shanghai"

jwt:
  secret: "personal_bill"
  timeout: 60

